# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'MJExtension', '~> 3.0.13'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'IQKeyboardManager', '~> 4.0.3'
    pod 'Masonry', '~> 1.1.0'
    
    #友盟
    #基础库
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    # 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'
    

end
